version: "3.3"

services:

  db:
    image: mongo:4.4.6
    env_file:
      - .env
    volumes:
      - ./mongo-data:/data/db

  web:
    build: ./app
    volumes:
      - media_volume:/usr/src/app/images
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - media_volume:/usr/src/app/images
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  media_volume: