version: "3.3"

services:

  db:
    image: mongo:4.4.6
    env_file:
      - .env
    volumes:
      - ./mongo-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: ./app
    volumes:
      - media_volume:/usr/src/app/images
    env_file:
      - .env
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build: ./nginx
    volumes:
      - media_volume:/usr/src/app/images
    ports:
      - 81:81
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  media_volume:
